/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RealtimeRouteImport } from './routes/realtime'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as SettingsAiStatusRouteImport } from './routes/settings.ai-status'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAutosaveRouteImport } from './routes/settings.autosave'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsCatalogImportRouteImport } from './routes/settings.catalog-import'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsProtocolsRouteImport } from './routes/settings.protocols'
import { Route as SettingsRateLimitsRouteImport } from './routes/settings.rate-limits'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsSecurityMonitorRouteImport } from './routes/settings.security-monitor'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as ProjectsProjectIdBomRouteImport } from './routes/projects.$projectId.bom'
import { Route as ProjectsProjectIdExportRouteImport } from './routes/projects.$projectId.export'
import { Route as ApiPublicIotIngestRouteImport } from './routes/api/public/iot.ingest'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp.webhook'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtimeRoute = RealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiStatusRoute = SettingsAiStatusRouteImport.update({
  id: '/ai-status',
  path: '/ai-status',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAutosaveRoute = SettingsAutosaveRouteImport.update({
  id: '/autosave',
  path: '/autosave',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCatalogImportRoute = SettingsCatalogImportRouteImport.update({
  id: '/catalog-import',
  path: '/catalog-import',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProtocolsRoute = SettingsProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRateLimitsRoute = SettingsRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityMonitorRoute = SettingsSecurityMonitorRouteImport.update({
  id: '/security-monitor',
  path: '/security-monitor',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectIdBomRoute = ProjectsProjectIdBomRouteImport.update({
  id: '/$projectId/bom',
  path: '/$projectId/bom',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdExportRoute = ProjectsProjectIdExportRouteImport.update({
  id: '/$projectId/export',
  path: '/$projectId/export',
  getParentRoute: () => ProjectsRoute,
} as any)
const ApiPublicIotIngestRoute = ApiPublicIotIngestRouteImport.update({
  id: '/api/public/iot/ingest',
  path: '/api/public/iot/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp/webhook',
  path: '/api/public/mp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/catalog': typeof CatalogRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/realtime': typeof RealtimeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/workspace': typeof WorkspaceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/ai-status': typeof SettingsAiStatusRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/autosave': typeof SettingsAutosaveRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/catalog-import': typeof SettingsCatalogImportRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/protocols': typeof SettingsProtocolsRoute
  '/settings/rate-limits': typeof SettingsRateLimitsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/security-monitor': typeof SettingsSecurityMonitorRoute
  '/settings/team': typeof SettingsTeamRoute
  '/projects/$projectId/bom': typeof ProjectsProjectIdBomRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/api/public/iot/ingest': typeof ApiPublicIotIngestRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/catalog': typeof CatalogRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/realtime': typeof RealtimeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/workspace': typeof WorkspaceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/ai-status': typeof SettingsAiStatusRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/autosave': typeof SettingsAutosaveRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/catalog-import': typeof SettingsCatalogImportRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/protocols': typeof SettingsProtocolsRoute
  '/settings/rate-limits': typeof SettingsRateLimitsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/security-monitor': typeof SettingsSecurityMonitorRoute
  '/settings/team': typeof SettingsTeamRoute
  '/projects/$projectId/bom': typeof ProjectsProjectIdBomRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/api/public/iot/ingest': typeof ApiPublicIotIngestRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/catalog': typeof CatalogRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/realtime': typeof RealtimeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/workspace': typeof WorkspaceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/ai-status': typeof SettingsAiStatusRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/autosave': typeof SettingsAutosaveRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/catalog-import': typeof SettingsCatalogImportRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/protocols': typeof SettingsProtocolsRoute
  '/settings/rate-limits': typeof SettingsRateLimitsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/security-monitor': typeof SettingsSecurityMonitorRoute
  '/settings/team': typeof SettingsTeamRoute
  '/projects/$projectId/bom': typeof ProjectsProjectIdBomRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/api/public/iot/ingest': typeof ApiPublicIotIngestRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/analytics'
    | '/catalog'
    | '/chat'
    | '/clients'
    | '/dashboard'
    | '/digital-twin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/realtime'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/workspace'
    | '/auth/callback'
    | '/clients/$clientId'
    | '/invite/$token'
    | '/settings/ai-status'
    | '/settings/appearance'
    | '/settings/autosave'
    | '/settings/billing'
    | '/settings/catalog-import'
    | '/settings/diagnostics'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/protocols'
    | '/settings/rate-limits'
    | '/settings/security'
    | '/settings/security-monitor'
    | '/settings/team'
    | '/projects/$projectId/bom'
    | '/projects/$projectId/export'
    | '/api/public/iot/ingest'
    | '/api/public/mp/webhook'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/analytics'
    | '/catalog'
    | '/chat'
    | '/clients'
    | '/dashboard'
    | '/digital-twin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/realtime'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/workspace'
    | '/auth/callback'
    | '/clients/$clientId'
    | '/invite/$token'
    | '/settings/ai-status'
    | '/settings/appearance'
    | '/settings/autosave'
    | '/settings/billing'
    | '/settings/catalog-import'
    | '/settings/diagnostics'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/protocols'
    | '/settings/rate-limits'
    | '/settings/security'
    | '/settings/security-monitor'
    | '/settings/team'
    | '/projects/$projectId/bom'
    | '/projects/$projectId/export'
    | '/api/public/iot/ingest'
    | '/api/public/mp/webhook'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/analytics'
    | '/catalog'
    | '/chat'
    | '/clients'
    | '/dashboard'
    | '/digital-twin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/realtime'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/workspace'
    | '/auth/callback'
    | '/clients/$clientId'
    | '/invite/$token'
    | '/settings/ai-status'
    | '/settings/appearance'
    | '/settings/autosave'
    | '/settings/billing'
    | '/settings/catalog-import'
    | '/settings/diagnostics'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/protocols'
    | '/settings/rate-limits'
    | '/settings/security'
    | '/settings/security-monitor'
    | '/settings/team'
    | '/projects/$projectId/bom'
    | '/projects/$projectId/export'
    | '/api/public/iot/ingest'
    | '/api/public/mp/webhook'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CatalogRoute: typeof CatalogRoute
  ChatRoute: typeof ChatRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RealtimeRoute: typeof RealtimeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicIotIngestRoute: typeof ApiPublicIotIngestRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtime': {
      id: '/realtime'
      path: '/realtime'
      fullPath: '/realtime'
      preLoaderRoute: typeof RealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ai-status': {
      id: '/settings/ai-status'
      path: '/ai-status'
      fullPath: '/settings/ai-status'
      preLoaderRoute: typeof SettingsAiStatusRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/autosave': {
      id: '/settings/autosave'
      path: '/autosave'
      fullPath: '/settings/autosave'
      preLoaderRoute: typeof SettingsAutosaveRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/catalog-import': {
      id: '/settings/catalog-import'
      path: '/catalog-import'
      fullPath: '/settings/catalog-import'
      preLoaderRoute: typeof SettingsCatalogImportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/protocols': {
      id: '/settings/protocols'
      path: '/protocols'
      fullPath: '/settings/protocols'
      preLoaderRoute: typeof SettingsProtocolsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/rate-limits': {
      id: '/settings/rate-limits'
      path: '/rate-limits'
      fullPath: '/settings/rate-limits'
      preLoaderRoute: typeof SettingsRateLimitsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security-monitor': {
      id: '/settings/security-monitor'
      path: '/security-monitor'
      fullPath: '/settings/security-monitor'
      preLoaderRoute: typeof SettingsSecurityMonitorRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectId/bom': {
      id: '/projects/$projectId/bom'
      path: '/$projectId/bom'
      fullPath: '/projects/$projectId/bom'
      preLoaderRoute: typeof ProjectsProjectIdBomRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/export': {
      id: '/projects/$projectId/export'
      path: '/$projectId/export'
      fullPath: '/projects/$projectId/export'
      preLoaderRoute: typeof ProjectsProjectIdExportRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/api/public/iot/ingest': {
      id: '/api/public/iot/ingest'
      path: '/api/public/iot/ingest'
      fullPath: '/api/public/iot/ingest'
      preLoaderRoute: typeof ApiPublicIotIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp/webhook': {
      id: '/api/public/mp/webhook'
      path: '/api/public/mp/webhook'
      fullPath: '/api/public/mp/webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdBomRoute: typeof ProjectsProjectIdBomRoute
  ProjectsProjectIdExportRoute: typeof ProjectsProjectIdExportRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdBomRoute: ProjectsProjectIdBomRoute,
  ProjectsProjectIdExportRoute: ProjectsProjectIdExportRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAiStatusRoute: typeof SettingsAiStatusRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsAutosaveRoute: typeof SettingsAutosaveRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsCatalogImportRoute: typeof SettingsCatalogImportRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsProtocolsRoute: typeof SettingsProtocolsRoute
  SettingsRateLimitsRoute: typeof SettingsRateLimitsRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSecurityMonitorRoute: typeof SettingsSecurityMonitorRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAiStatusRoute: SettingsAiStatusRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsAutosaveRoute: SettingsAutosaveRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsCatalogImportRoute: SettingsCatalogImportRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsProtocolsRoute: SettingsProtocolsRoute,
  SettingsRateLimitsRoute: SettingsRateLimitsRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSecurityMonitorRoute: SettingsSecurityMonitorRoute,
  SettingsTeamRoute: SettingsTeamRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  CatalogRoute: CatalogRoute,
  ChatRoute: ChatRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RealtimeRoute: RealtimeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  WorkspaceRoute: WorkspaceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicIotIngestRoute: ApiPublicIotIngestRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
