import { createEmptyDoc, makeNode } from "../lib/diagram/model";
import { applyCommand, cmd } from "../lib/diagram/commands";
import { buildMultifilarCommands } from "../lib/diagram/multifilar";
let doc = createEmptyDoc();
doc = { ...doc, metadata: { ...doc.metadata, title: "Roundtrip Multifilar" } };
const q = makeNode({ sheet: "unifilar", params: { kind: "breaker", in_A: 20, curve: "C", poles: 4 }, position: { x: 0, y: 0 }, label: "QF1" });
const m = makeNode({ sheet: "unifilar", params: { kind: "motor", power_kW: 5, voltage_V: 380, startMethod: "DOL" }, position: { x: 300, y: 0 }, label: "M1" });
const l = makeNode({ sheet: "unifilar", params: { kind: "lamp", power_W: 15, voltage_V: 220 }, position: { x: 300, y: 200 }, label: "HL1" });
doc = applyCommand(doc, { type: "Batch", commands: [{ type: "AddNode", node: q }, { type: "AddNode", node: m }, { type: "AddNode", node: l }] });
doc = applyCommand(doc, cmd.addEdge({ sheet: "unifilar", source: q.id, target: m.id, kind: "power" }));
doc = applyCommand(doc, cmd.addEdge({ sheet: "unifilar", source: q.id, target: l.id, kind: "power" }));
doc = applyCommand(doc, { type: "Batch", commands: buildMultifilarCommands(doc) });
const snapshot = { schemaVersion: 2, project: { nodes: [], edges: [], tags: {}, scadaLayout: { nodes: [], edges: [] } }, voltai: { components: [], edges: [] }, editor: { tags: {}, rungs: [], fbdNodes: [], fbdEdges: [] }, diagram: doc };
await Bun.write("/tmp/snapshot.json", JSON.stringify(snapshot));
console.log("edges multifilar:", Object.values(doc.edges).filter(e=>e.sheet==="multifilar").map(e=>e.circuitConfig).join(","));
